name: Release DevOps on Heroku

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Heroku CLI
      run: sudo npm install -g heroku

    - name: token
      run: heroku auth:token

    - name: Login to Heroku
      run: docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
    
    - name: Build and push
      run: heroku container:push web && heroku container:release web